## NBA Draft Lottery

Plackett - Luce model

Import required libraries

In [31]:
import pandas as pd
import numpy
from numpy import *

Initial probabilites(Hypothetical)

In [32]:
initialp = [0.114,0.113,0.112,.111,.099,.089,.079,.069,.059,.049,.039,.029,.019,.009,.006,.004]

In [33]:
def find(probs,rem_probs,rest_p):
    for i in range(11):
        #print(probs)
        nonzeros = [j for j,e in enumerate(probs) if e!=0]
        team = min(nonzeros)
        #print(team)
        rem_probs[i][team] = rem_probs[i][team]+rest_p
        #print(rem_probs)
        probs[team] = 0
        
    return rem_probs

In [34]:
secondp = [0.]*16
thirdp = [0.]*16
fourthp = [0.]*16
fifthp = [0.]*16
#r_probs = [[0 for i in range(16)] for j in range(11)]
r_probs = [[0]*16 for _ in range(11)]

In [35]:
for i in range(16):
    first_removed = initialp[:i] + [0.] + initialp[i+1:]
    #print(first_removed)
    total_prob = sum(first_removed)
    c_p = [initialp[i]*x/total_prob for x in first_removed]
    #print(c_p[0])
    secondp = [float("{0:.5f}".format(x+y)) for x,y in zip(secondp,c_p)]
    
    for j in range(16):
        if i!=j:
            second = first_removed[:j]+[0.]+first_removed[j+1:]
            total = sum(second)
            cp_2 = [c_p[j]*x/total for x in second]
            thirdp = [float("{0:.5f}".format(x+y)) for x,y in zip(thirdp,cp_2)]
            
            for k in range(16):
                if i!=k and j!=k:
                    third = second[:k]+[0.]+second[k+1:]
                    total_1 = sum(third)
                    cp_3 = [cp_2[k]*x/total_1 for x in third]
                    fourthp = [float("{0:.5f}".format(x+y)) for x,y in zip(fourthp,cp_3)]
                    
                    for l in range(16):
                        if i!= l and j!=l and k!=l:
                            fourth = third[:l]+[0.]+third[l+1:]
                            total_2 = sum(fourth)
                            cp_4 = [cp_3[l]*x/total_2 for x in fourth]
                            fifthp = [x+y for x,y in zip(fifthp,cp_4)]
                    
                            for m in range(16):
                                if i!=m and j!=m and k!=m and l!=m:
                                #if len(unique([i,j,k,l,m])) == 5:
                                        #print(cp_4[l])
                                        restProb = cp_4[m]
                                        #print(restProb)
                                        f_removed = fourth[:m]+[0.]+fourth[m+1:]
                                        #print(f_removed)
                                        r_probs = find(f_removed,r_probs,restProb)

## Probabilities

In [62]:
probab = pd.DataFrame([secondp,thirdp, fourthp,fifthp]).T
probab.rename(index=str, columns={0: "secondp",1: "thirdp",2: "fourthp",3: "fifthp"})

    secondp   thirdp  fourthp    fifthp
0   0.11048  0.10654  0.10113  0.097122
1   0.10964  0.10594  0.10066  0.096856
2   0.10883  0.10524  0.10010  0.096583
3   0.10799  0.10459  0.09961  0.096302
4   0.09781  0.09643  0.09338  0.092286
5   0.08901  0.08884  0.08745  0.087957
6   0.07993  0.08088  0.08080  0.082650
7   0.07065  0.07236  0.07312  0.076293
8   0.06106  0.06333  0.06456  0.068822
9   0.05126  0.05377  0.05517  0.060187
10  0.04125  0.04372  0.04513  0.050347
11  0.03097  0.03323  0.03428  0.039270
12  0.02049  0.02216  0.02293  0.026936
13  0.00980  0.01073  0.01021  0.013332
14  0.00654  0.00707  0.00611  0.009003
15  0.00437  0.00472  0.00330  0.006053

In [63]:
pd.DataFrame(r_probs)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.469749,0.273960,0.147744,0.071306,0.029955,0.007286,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
1,0.000000,0.198981,0.254418,0.229152,0.178902,0.103400,0.035148,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.073992,0.155605,0.225853,0.247828,0.200783,0.095940,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.023330,0.078715,0.163778,0.252457,0.286552,0.195169,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.006641,0.032707,0.095718,0.205871,0.330166,3.288970e-01,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.000000,0.001629,0.011286,0.045860,0.138036,3.188260e-01,4.843636e-01,0.000000e+00,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000330,0.003156,0.017764,7.576331e-02,2.601735e-01,6.428127e-01,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000052,0.000683,5.354113e-03,3.310375e-02,1.774453e-01,0.783362,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000006,1.065391e-04,1.185415e-03,1.107045e-02,0.100736,0.886896,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.361609e-07,1.100527e-05,1.822778e-04,0.002859,0.057687,0.939260,0.000000
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,1.638867e-08,6.124179e-07,0.000017,0.000634,0.023971,0.975377

In [41]:
draft_df = pd.DataFrame()

Total number of seeds for 16 teams(14 non-playoff and 2 playoff teams)

In [42]:
seed = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]

In [43]:
draft_df['Seed'] = seed

Hypothetical chances

In [44]:
draft_df['Chances'] = [114,113,112,111,99,89,79,69,59,49,39,29,19,9,6,4]

Defining columns for the dataframe

In [45]:
draft_df['1st'], draft_df['2nd'], draft_df['3rd'], draft_df['4th'], draft_df['5th'] = [initialp,secondp,thirdp,fourthp,fifthp]

In [46]:
draft_df['6th'] = r_probs[0]

In [47]:
draft_df['7th'],draft_df['8th'],draft_df['9th'],draft_df['10th'],draft_df['11th'],draft_df['12th'],draft_df['13th'] = [r_probs[i] for i in range(1,8)]

In [48]:
draft_df['14th'],draft_df['15th'],draft_df['16th'] = [r_probs[8],r_probs[9],r_probs[10]]

In [49]:
draft_df['7th'].replace(0.00000,'-',inplace=True)

In [50]:
l = ['6th','8th','9th','10th','11th','12th','13th','14th','15th','16th']

Replace probability 0 with -

In [51]:
for i in l:
    draft_df[i].replace(0.00000,'-',inplace=True)

## Final dataframe

In [52]:
draft_df

,Seed,Chances,1st,2nd,3rd,4th,5th,6th,7th,8th,9th,10th,11th,12th,13th,14th,15th,16th
0,1,114,0.114,0.11048,0.10654,0.10113,0.097122,0.469749,-,-,-,-,-,-,-,-,-,-
1,2,113,0.113,0.10964,0.10594,0.10066,0.096856,0.27396,0.198981,-,-,-,-,-,-,-,-,-
2,3,112,0.112,0.10883,0.10524,0.10010,0.096583,0.147744,0.254418,0.0739924,-,-,-,-,-,-,-,-
3,4,111,0.111,0.10799,0.10459,0.09961,0.096302,0.071306,0.229152,0.155605,0.0233295,-,-,-,-,-,-,-
4,5,99,0.099,0.09781,0.09643,0.09338,0.092286,0.0299554,0.178902,0.225853,0.0787145,0.00664084,-,-,-,-,-,-
5,6,89,0.089,0.08901,0.08884,0.08745,0.087957,0.00728613,0.1034,0.247828,0.163778,0.0327069,0.00162863,-,-,-,-,-
6,7,79,0.079,0.07993,0.08088,0.08080,0.082650,-,0.035148,0.200783,0.252457,0.0957183,0.0112858,0.00032993,-,-,-,-
7,8,69,0.069,0.07065,0.07236,0.07312,0.076293,-,-,0.0959398,0.286552,0.205871,0.04586,0.00315644,5.20816e-05,-,-,-
8,9,59,0.059,0.06106,0.06333,0.06456,0.068822,-,-,-,0.195169,0.330166,0.138036,0.0177641,0.000682618,5.91953e-06,-,-
9,10,49,0.049,0.05126,0.05377,0.05517,0.060187,-,-,-,-,0.328897,0.318826,0.0757633,0.00535411,0.000106539,4.36161e-07,-
10,11,39,0.039,0.04125,0.04372,0.04513,0.050347,-,-,-,-,-,0.484364,0.260174,0.0331037,0.00118542,1.10053e-05,1.63887e-08
11,12,29,0.029,0.03097,0.03323,0.03428,0.039270,-,-,-,-,-,-,0.642813,0.177445,0.0110704,0.000182278,6.12418e-07
12,13,19,0.019,0.02049,0.02216,0.02293,0.026936,-,-,-,-,-,-,-,0.783362,0.100736,0.00285924,1.70513e-05
13,14,9,0.009,0.00980,0.01073,0.01021,0.013332,-,-,-,-,-,-,-,-,0.886896,0.0576872,0.000634341
14,15,6,0.006,0.00654,0.00707,0.00611,0.009003,-,-,-,-,-,-,-,-,-,0.93926,0.0239708
15,16,4,0.004,0.00437,0.00472,0.00330,0.006053,-,-,-,-,-,-,-,-,-,-,0.975377

## Saving dataframe to csv

In [28]:
draft_df.to_csv('DraftProbabilityTable.csv',index= False)